spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/weolbu
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  messages:
    basename: business-errors
    encoding: UTF-8
